if (self.CavalryLogger) { CavalryLogger.start_js(["MbbeH"]); }

__d("MWChatBusinessWelcomePageQuery.graphql",["relay-runtime"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"pageID"}],b={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};b=[{alias:null,args:[{kind:"Variable",name:"page_id",variableName:"pageID"}],concreteType:"MessengerBusinessWelcomePageResult",kind:"LinkedField",name:"messenger_business_welcome_page_info",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"pages_greeting_content",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"pages_greeting_should_show",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"page_responsiveness",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"should_show_responsive",storageKey:null},{alias:null,args:null,concreteType:"MessengerCallToAction",kind:"LinkedField",name:"null_state_cta",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"action_title",storageKey:null},b],storageKey:null},{alias:null,args:null,concreteType:"PageOneClickMessageInfo",kind:"LinkedField",name:"icebreakers",plural:!0,selections:[{alias:null,args:null,kind:"ScalarField",name:"message",storageKey:null}],storageKey:null},{alias:null,args:null,concreteType:"MessengerBusinessPageIcebreakerCta",kind:"LinkedField",name:"icebreaker_ctas",plural:!0,selections:[b,{alias:null,args:null,kind:"ScalarField",name:"title",storageKey:null}],storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"MWChatBusinessWelcomePageQuery",selections:b,type:"Query",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"MWChatBusinessWelcomePageQuery",selections:b},params:{id:"3242961722496596",metadata:{},name:"MWChatBusinessWelcomePageQuery",operationKind:"query",text:null}}}();a.params.id!=null&&b("relay-runtime").PreloadableQueryRegistry.set(a.params.id,a);e.exports=a}),null);
__d("MWUIAddParticipantsToGroup.bs",["requireCond","cr:1499534"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1499534").useHook;f.$MWLSAddParticipantsToGroup$OR$MWMSAddParticipantsToGroup$requireCond=b("cr:1499534");f.useHook=a}),null);
__d("MWChatBusinessWelcomePageQuery",["CometRelay","React","promiseDone","MWChatBusinessWelcomePageQuery.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(){var a=b("CometRelay").useRelayEnvironment();return h.useCallback(function(c,d){c=b("CometRelay").fetchQuery(a,i,{pageID:c}).toPromise().then(function(a){a=a==null?void 0:a.messenger_business_welcome_page_info;if(a==null){d(a);return}var b=a.icebreaker_ctas,c=a.icebreakers,e=a.null_state_cta,f=a.page_responsiveness,g=a.pages_greeting_content,h=a.pages_greeting_should_show;a=a.should_show_responsive;c=c.map(function(a,b){return a.message});b=b.map(function(a){return{id:a.id,title:a.title}});e=e!=null?{icebreaker_ctas:b,icebreakers:c,null_state_cta:{action_title:e.action_title,id:e.id},page_responsiveness:(e=f)!=null?e:"",pages_greeting_content:(e=g)!=null?e:"",pages_greeting_should_show:(e=h)!=null?e:!1,should_show_responsive:(e=a)!=null?e:!1}:{icebreaker_ctas:b,icebreakers:c,page_responsiveness:(e=f)!=null?e:"",pages_greeting_content:(b=g)!=null?b:"",pages_greeting_should_show:(c=h)!=null?c:!1,should_show_responsive:(f=a)!=null?f:!1};d(e);return});b("promiseDone")(c)},[a])}var i=g!==void 0?g:g=b("MWChatBusinessWelcomePageQuery.graphql")}),null);
__d("MWChatBusinessWelcomePageHook.bs",["bs_curry","React","bs_caml_option","MWChatBusinessWelcomePageQuery"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a,c){var d=g.useState(function(){}),e=d[1],f=b("MWChatBusinessWelcomePageQuery")();g.useEffect(function(){var d=0;typeof a==="string"||a.NAME!=="Page"?d=1:c?f(a.VAL,function(a){if(a===void 0)return b("bs_curry")._1(e,function(a){});var c=b("bs_caml_option").valFromOption(a);return b("bs_curry")._1(e,function(a){return b("bs_caml_option").some(c)})}):b("bs_curry")._1(e,function(a){});d===1&&b("bs_curry")._1(e,function(a){})},[a,c,f,e]);return d[0]}f.useMessengerBusinessWelcomePage=a}),null);
__d("MWChatHasTabContent.bs",["React","MWChatMultitabStateHook.bs","MWChatMultitabHasTabContent.bs"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("MWChatMultitabStateHook.bs").useHook_DEPRECATED(void 0);return g.useCallback(function(a){return b("MWChatMultitabHasTabContent.bs").get(c,a)},[c])}f.useHook=a}),null);
__d("MWChatBlurTab.bs",["React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){if(c!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,c,{TAG:7,_0:a})},[c])}f.useHook=a}),null);
__d("MWChatFocusTab.bs",["React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){if(c!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,c,{TAG:8,_0:a})},[c])}f.useHook=a}),null);
__d("MWUILoadIsDisabledComposerThreadLevel.bs",["requireCond","cr:1633761"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1633761").useHook;f.$MWLSLoadIsDisabledComposerThreadLevel$OR$MWMSLoadIsDisabledComposerThreadLevel$requireCond=b("cr:1633761");f.useHook=a}),null);
__d("MWUISendCometPostback.bs",["requireCond","cr:1503273"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1503273").useSendCometPostback;f.$MWLSSendCometPostback$OR$MWMSSendCometPostback$requireCond=b("cr:1503273");f.useSendCometPostback=a}),null);
__d("MWUIWebUrlCtaHandler.bs",["requireCond","cr:1503224"],(function(a,b,c,d,e,f){"use strict";b("cr:1503224");a=b("cr:1503224").useShowWebViewDialog;f.$MWLSWebUrlCtaHandler$OR$MWMSWebUrlCtaHandler$requireCond=b("cr:1503224");f.useShowWebViewDialog=a}),null);
__d("MWChatTabGroupWarningPolicy.bs",["FBID.bs","bs_curry","React","bs_belt_Set","JSResource","CurrentUser","MWUIBlockStatus.bs","useCometLazyDialog","MWThread_DEPRECATED.bs","MWUICurrentThreadParticipants.bs"],(function(a,b,c,d,e,f){"use strict";var g=b("React"),h={contents:b("bs_belt_Set").make(b("FBID.bs"))};function a(a){return a.has(b("CurrentUser").getID())}function i(a){return Array.from(a.keys()).sort().join(":")}function c(a,c,d){var e=b("bs_curry")._1(b("MWUICurrentThreadParticipants.bs").useParticipants,void 0);c=i(e);var f=b("MWThread_DEPRECATED.bs").useIdExn(void 0),j=b("bs_curry")._1(b("MWUIBlockStatus.bs").useBlockeesInThread,f),k=g.useState(function(){return!1}),l=k[1],m=k[0];k=b("useCometLazyDialog")(b("JSResource")("MWChatGroupEntranceWarningForJSResource.react").__setRef("MWChatTabGroupWarningPolicy.bs"));var n=k[0],o=function(a){if(typeof f==="string"||f.NAME!=="Group")return;else{h.contents=b("bs_belt_Set").add(h.contents,f.VAL);return b("bs_curry")._1(d,void 0)}};g.useEffect(function(){if(typeof f!=="string"&&f.NAME==="Group"){var c=f.VAL;!m&&!b("bs_belt_Set").has(h.contents,c)&&e.has(b("CurrentUser").getID())&&j.length>0&&(n({blockeeIDs:j,onLeaveGroup:a,onOptIn:o,onClose:function(a){return b("bs_curry")._1(l,function(a){return!1})},threadFbid:c},function(a){return b("bs_curry")._1(l,function(a){return!1})}),b("bs_curry")._1(l,function(a){return!0}))}},[f,c])}f.optedInThreads=h;f.viewerInThread=a;f.hashParticipants=i;f.useGroupEntranceWarningEffect=c}),null);
__d("MWUIFetchMessagesPage.bs",["requireCond","cr:1435663"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1435663").useFetchMessagesPage;f.$MWLSFetchMessagesPage$OR$MWMSFetchMessagesPage$requireCond=b("cr:1435663");f.useFetchMessagesPage=a}),null);
__d("MWUIContactCapabilities.bs",["requireCond","cr:1500017"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1500017").useCapabilities;c=b("cr:1500017").isVerified;f.$MWLSContactCapabilities$OR$MWMSContactCapabilities$requireCond=b("cr:1500017");f.useCapabilities=a;f.isVerified=c}),null);
__d("MWUIThreadHasLeftGroup.bs",["requireCond","cr:1549237"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1549237").useHook;f.$MWLSThreadHasLeftGroup$OR$MWMSThreadHasLeftGroup$requireCond=b("cr:1549237");f.useHook=a}),null);
__d("MWUIUpdateParticipantNickname.bs",["requireCond","cr:1498778"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1498778").useHook;f.$MWLSUpdateParticipantNickname$OR$MWMSUpdateParticipantNickname$requireCond=b("cr:1498778");f.useHook=a}),null);
__d("MWUIThreadHasThread.bs",["requireCond","cr:1549238"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1549238").useHook;f.$MWLSThreadHasThread$OR$MWMSThreadHasThread$requireCond=b("cr:1549238");f.useHook=a}),null);
__d("MWLSCannotReplyReason.bs",["React","SkytaleDB","bs_belt_Option","MWThreadKey.bs","SkytaleDBHook.bs","SkytaleDBQuery.bs","SkytaleDBQuerySubscriptionHook.bs"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("SkytaleDBHook.bs").useHook(void 0),d=b("MWThreadKey.bs").useIdMemoizedExn(void 0);return b("bs_belt_Option").getWithDefault(b("SkytaleDBQuerySubscriptionHook.bs").useFirst(g.useMemo(function(){return b("SkytaleDBQuery.bs").map(b("SkytaleDBQuery.bs").getKeyRange(b("SkytaleDB").table(c,"threads").asc,{hd:d,tl:0}),function(a){return a.v})},[c,d])),void 0)}f.useCannotReplyReason=a}),null);
__d("MWUICannotReplyReason.bs",["requireCond","cr:1843681"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1843681").useCannotReplyReason;f.$MWLSCannotReplyReason$OR$MWMSCannotReplyReason$requireCond=b("cr:1843681");f.useCannotReplyReason=a}),null);