if (self.CavalryLogger) { CavalryLogger.start_js(["Ccmwh"]); }

__d("RoomCardImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744277");c=b("FalcoLoggerInternal").create("room_card_impression",a);e.exports=c}),null);
__d("RoomCardTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744280");c=b("FalcoLoggerInternal").create("room_card_tap",a);e.exports=c}),null);
__d("RoomCreateTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744282");c=b("FalcoLoggerInternal").create("room_create_tap",a);e.exports=c}),null);
__d("RoomCreationFlowSuccessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744287");c=b("FalcoLoggerInternal").create("room_creation_flow_success",a);e.exports=c}),null);
__d("RoomEmptyCardSheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744293");c=b("FalcoLoggerInternal").create("room_empty_card_sheet_impression",a);e.exports=c}),null);
__d("RoomGroupRoomListViewImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744296");c=b("FalcoLoggerInternal").create("room_group_room_list_view_impression",a);e.exports=c}),null);
__d("RoomGroupRoomListViewItemTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744297");c=b("FalcoLoggerInternal").create("room_group_room_list_view_item_tap",a);e.exports=c}),null);
__d("RoomGroupRoomRhcImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744298");c=b("FalcoLoggerInternal").create("room_group_room_rhc_impression",a);e.exports=c}),null);
__d("RoomInterestTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744299");c=b("FalcoLoggerInternal").create("room_interest_tap",a);e.exports=c}),null);
__d("RoomJoinTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744302");c=b("FalcoLoggerInternal").create("room_join_tap",a);e.exports=c}),null);
__d("RoomLobbySheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744305");c=b("FalcoLoggerInternal").create("room_lobby_sheet_impression",a);e.exports=c}),null);
__d("RoomMessageTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744314");c=b("FalcoLoggerInternal").create("room_message_tap",a);e.exports=c}),null);
__d("RoomPromotionUnitImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744315");c=b("FalcoLoggerInternal").create("room_promotion_unit_impression",a);e.exports=c}),null);
__d("RoomPromotionUnitTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744316");c=b("FalcoLoggerInternal").create("room_promotion_unit_tap",a);e.exports=c}),null);
__d("RoomSelfCardButtonTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744320");c=b("FalcoLoggerInternal").create("room_self_card_button_tap",a);e.exports=c}),null);
__d("RoomSelfCardTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744321");c=b("FalcoLoggerInternal").create("room_self_card_tap",a);e.exports=c}),null);
__d("RoomSettingSheetImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744323");c=b("FalcoLoggerInternal").create("room_setting_sheet_impression",a);e.exports=c}),null);
__d("RoomTrayImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744329");c=b("FalcoLoggerInternal").create("room_tray_impression",a);e.exports=c}),null);
__d("RoomUpdateTapFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744332");c=b("FalcoLoggerInternal").create("room_update_tap",a);e.exports=c}),null);