if (self.CavalryLogger) { CavalryLogger.start_js(["x+Q5c"]); }

__d("FocusTable.bs",["FocusTable.react"],(function(a,b,c,d,e,f){"use strict";function a(a){a=b("FocusTable.react").createFocusTable(a.query);var c=a[2],d=a[1];a=a[0];var e={make:a},f={make:d},g={make:c};return{table:a,row:d,cell:c,Table:e,Row:f,Cell:g}}f.Make=a}),null);
__d("MWChatMessageTableFocusTable.bs",["fbt","React","CometKeys","FocusTable.bs","CometComponentWithKeyCommands.react"],(function(a,b,c,d,e,f,g){"use strict";var h=b("React"),i="messages_table";function a(a,b,c){return c.dataset.scope===i}d=b("FocusTable.bs").Make({query:a});var j={key:(e=b("CometKeys")).UP},k={key:e.DOWN},l={key:e.LEFT};e={key:e.RIGHT};var m=[{command:j,description:g._("Previous item"),handler:function(a){}},{command:k,description:g._("Next item"),handler:function(a){}},{command:l,description:g._("Next item"),handler:function(a){}},{command:e,description:g._("Previous item"),handler:function(a){}}];function c(a){a=a.children;return h.jsx(b("CometComponentWithKeyCommands.react"),{commandConfigs:m,xstyle:!1,children:a})}var n,o,p;g=c;f.scopeID=i;f.scopeQuery=a;f.Table_=d;f.Table=n;f.Row=o;f.Cell=p;f.keyUp=j;f.keyDown=k;f.keyLeft=l;f.keyRight=e;f.commandConfigs=m;f.keyCommands=g}),null);
__d("MWChatMessageCellFocusTable.bs",["fbt","React","CometKeys","FocusTable.bs","focusScopeQueries","MWChatMessageTableFocusTable.bs","CometComponentWithKeyCommands.react"],(function(a,b,c,d,e,f,g){"use strict";var h=b("React");c=b("focusScopeQueries").tabbableScopeQuery;d=b("FocusTable.bs").Make({query:c});var i={key:b("CometKeys").ESCAPE},j={key:b("CometKeys").ENTER},k={key:b("CometKeys").SPACE},l=g._("Exit focus region"),m=g._("Enter focus region");function a(a){var c=a.onEscape,d=a.onEnter,e=a.onSpace;a=a.children;var f=[];c!==void 0&&f.push({command:i,description:l,handler:c});d!==void 0&&f.push({command:j,description:m,handler:d});e!==void 0&&f.push({command:k,description:m,handler:e});return h.jsx(b("CometComponentWithKeyCommands.react"),{commandConfigs:b("MWChatMessageTableFocusTable.bs").commandConfigs.concat(f),xstyle:!1,children:a})}var n,o,p;e=a;f.Table_=d;f.Table=n;f.Row=o;f.Cell=p;f.$$escape=i;f.enter=j;f.space=k;f.exitFbt=l;f.enterFbt=m;f.keyCommands=e}),null);
__d("MWUIThreadCapabilities.bs",["requireCond","cr:1463902"],(function(a,b,c,d,e,f){"use strict";c=(a=b("cr:1463902")).useCapabilities;d=a.canSendGif;e=a.canSendPayment;b=a.canCreatePoll;var g=a.canDisplayActorTypeInThreadViewHeader,h=a.canCustomizeEmoji,i=a.canCustomizeNicknames,j=a.canCustomizeTheme,k=a.canCreateGroup,l=a.canRtcVideoCall,m=a.canRtcVoiceCall,n=a.canSendFile,o=a.canSendRoom,p=a.canSendAudioClip,q=a.canSendQuickCamAttachment,r=a.canDisableLinks;f.$MWLSThreadCapabilities$OR$MWMSThreadCapabilities$requireCond=a;f.useCapabilities=c;f.canSendGif=d;f.canSendPayment=e;f.canCreatePoll=b;f.canDisplayActorTypeInThreadViewHeader=g;f.canCustomizeEmoji=h;f.canCustomizeNicknames=i;f.canCustomizeTheme=j;f.canCreateGroup=k;f.canRtcVideoCall=l;f.canRtcVoiceCall=m;f.canSendFile=n;f.canSendRoom=o;f.canSendAudioClip=p;f.canSendQuickCamAttachment=q;f.canDisableLinks=r}),null);
__d("MWUIThreadMuteExpireTimeMs.bs",["requireCond","cr:1614090"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1614090").useHook;f.$MWLSThreadMuteExpireTimeMs$OR$MWMSThreadMuteExpireTimeMs$requireCond=b("cr:1614090");f.useHook=a}),null);
__d("LsMessengerThreadDamagingActionsEntryPoint",[],(function(a,b,c,d,e,f){a=Object.freeze({ADD_BLOCK:0,BLOCK_COMPOSER:1,BLOCK_VIEW:2,BLOCKED_USER_ROW:3,DECLINE_MR:4,FILTERED_REQUEST:5,FRX:6,FRX_CONFIRMATION:7,GROUP_BLOCK_MEMBER:8,GROUP_MESSAGE_CONTACT_MENU:9,GROUP_WARNING_DIALOG:10,INBOX_THREAD_ACTIONS:11,INBOX_THREAD_LIST:12,MANAGE_MESSAGES:13,MESSAGE_REQUEST:14,OMNI_PICKER:15,PAGE_REPORT:16,PROACTIVE_WARNING:17,PROFILE:18,THREAD_SETTINGS:19,THREAD_SETTINGS_GROUP_MEMBERS:20,THREAD_SETTINGS_TITLE_BAR_MENU:21,THREAD_VIEW:22,THREAD_VIEW_BLOCKER_COMPOSER:23,PAGE_MENU:24,UNAVAILABLE_COMPOSER:25,UPSELL_BLOCK_NOTIFICATION:26,PSEUDO_BLOCK_WARNING_DIALOG:27,SUGGESTED_BLOCK:28,PENDING_THREAD_LIST:29,SPAM_THREAD_LIST:30,SUPPORT_INBOX_REPORT_IN_REVIEW:31,SUPPORT_INBOX_REPORT_REVIEWED:32});e.exports=a}),null);
__d("LsMessengerThreadDamagingActionsSource",[],(function(a,b,c,d,e,f){a=Object.freeze({BLOCKED_PEOPLE:0,CANONICAL_THREAD:1,EMPTY_THREAD:2,GROUP_THREAD:3,INCOMING_CALL:4,PAGE:5,STORY:6,TINCAN_THREAD:7,USER:8,CARRIER_THREAD:9,MESSAGE_REQUEST:10,SUPPORT_INBOX:11,DISAPPEARING_THREAD:12});e.exports=a}),null);
__d("LsMessengerThreadDamagingActionsSourceOwner",[],(function(a,b,c,d,e,f){a=Object.freeze({MCI:0,MBI:1,RTC:2,HI:3});e.exports=a}),null);